# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Happy Cog Dev
tagline:             'Happy Cog'
description:         'Description here'
url:                 http://happycog.github.io/dev/
baseurl:             ''
gems:                 [jekyll-paginate]
gems:                 [github-pages]
paginate:            5

# About/contact
author:
  name:              Happy Cog
  url:               http://happycog.com/
  email:             email

# Custom vars
version:             1.0.0
