# Permalinks
permalink:           pretty

# Setup
title:               Happy Cog Development
tagline:             'Happy Cog'
description:         'Description here'
url:                 http://happycog.github.io/dev/
baseurl:             ''
# paginate:            5

# About/contact
author:
  name:              Happy Cog
  url:
  email:             

# Custom vars
version:             1.0.0
