# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Happy Cog Dev
tagline:             'Happy Cog'
description:         'Description here'
url:                 'https://happycog.github.io/dev'
baseurl:             'https://happycog.github.io/dev'
gems:                 [jekyll-paginate]
paginate:            5

# About/contact
author:
  name:              Happy Cog
  url:               http://happycog.com/
  email:             email

# Custom vars
version:             1.0.0

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
